### ISSUE TITLE
Error in FC32 kernel 5.8.4

### ISSUE THREAD

**Issue by rbras** [veeam/veeamsnap#12]
Veeam backup fails with:

Waiting for backup infrastructure resources availability                                                                   00:00:02        
      [error] Failed to create volume snapshot                                                                                   00:00:01        
      [error] Failed to take volume snapshot                                                                                                     
      [error] Failed to perform backup                                                                                                           
      [error] Invalid argument                                                                                                                   
      [error] Failed to execute IOCTL_TRACKING_ADD                                                                                               
      [error] Processing finished with errors at 2020-09-08 17:46:15 GMT

dmesg:

veeamsnap:tracking   Adding device [8:1] under tracking
Create tracker for device [8:1]. Start 0x800 sector, capacity 0x12c000 sectors
veeamsnap:cbt_map    CBT map create
veeamsnap:cbt_map    Allocate CBT map of 2400
veeamsnap:tracker    | ERR | Cannot make hook. make_request_fn is NULL.
veeamsnap:tracker    | ERR | Failed to create tracker for device [8:1]
veeamsnap:tracking   | ERR | Failed to create tracker. errno=-22
veeamsnap:blk        Device [8:1] was frozen
veeamsnap:blk        Device [8:1] was unfrozen
veeamsnap:blk        Device [8:1] was frozen
veeamsnap:blk        Device [8:1] was unfrozen

Best regards,

Raul

**Comment by veeam** [comment]
See Issue 10.
