### ISSUE TITLE
Can veeamsnap be used alone?

### ISSUE THREAD

**Issue by LightSlight** [veeam/veeamsnap#27]
Hello, 
   I want to know if my computer doesn't install the veeam agent for linux, this kernel module "veeamsnap" could be used alone for volume snapshot ?

**Comment by CodeImp** [comment]
Hi!
Good question.
In theory, nothing prevents you from accessing the module from user-space. The module is distributed under GPL-2.
But the problem is that there are no user-space open source libraries and  utilities to work with veeamsnap.
