### ISSUE TITLE
The veeamsnap project will be deprecated.

### ISSUE THREAD

**Issue by SergeiShtepa** [veeam/veeamsnap#30]
Veeam Agent for Linux 6.0 will contain [blksnap](https://github.com/veeam/blksnap). It is already available in VAL 6.0 TP and is recommended for lk 5.10 - 5.17.
On older kernels with a version up to 5.10, veeamsnap can still be used. Therefore, both modules will be used for a long time. But support for new kernel versions in the veeamsnap module is not expected.
Any feedback is welcome.

**Comment by joker234** [comment]
With Debian testing, Kernel 5.17, `veeamsnap` isn't working anymore. It would be nice if you could add some description on updating to the nonsnap version (`e.g. apt install veeam-nosnap`) which worked for me. Much better would be to add transititons to the [veeam debian packages](https://repository.veeam.com/backup/linux/agent/dpkg/debian/public/). I'm not sure of the specific process here, but I think there should be a way of depending on a specific kernel to be installed (e.g. `veeamsnap` depends on kernel < 5.17 and `veeam-nosnap` on kernel >= 5.10).

**Comment by SergeiShtepa** [comment]
The veeam-nosnap package cannot replace veeam with veeamsnap packages.
veeam-nosnap can be used for those cases when there is no need to create a snapshot.
VAL 6.0 will work with the blksnap module on new kernels.
For Debian Testing, I would advise waiting for VAL 6.0 beta.

**Comment by Fantu** [comment]
@SergeiShtepa I think can be useful mention in readme that this project is deprecated and link to blksnap for latest kernel compatibility and as new project supported

**Comment by SergeiShtepa** [comment]
@Fantu - Yep.

**Comment by veeam** [comment]
Since veeamsnap is deprecated, the issue is closed.
