### ISSUE TITLE
linux kernel 5.18 update possible?

### ISSUE THREAD

**Issue by csandazoltan** [veeam/veeamsnap#31]
I see that the supported kernels close at 5.16 rc6, but it doesn't hurt asking

Is there a chance that veaamsnap will be updated for 5.18? 
If this kernel is going to be a default, OMV 6 debian would not be possible to make snapshot backups, rolling back kernel is not gonna solve it if I reinstall an OS or do another machine
5.16 worked perfectly with dkms build

dkms build exits with a missing file error:

> DKMS make.log for veeamsnap-5.0.2.4567 for kernel 5.18.0-0.bpo.1-amd64 (x86_64)
Wed 22 Jun 12:06:04 CEST 2022
make: Entering directory '/usr/src/linux-headers-5.18.0-0.bpo.1-amd64'
  CC [M]  /var/lib/dkms/veeamsnap/5.0.2.4567/build/log.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.2.4567/build/mem_alloc.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.2.4567/build/sparse_bitmap.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.2.4567/build/container.o
In file included from /var/lib/dkms/veeamsnap/5.0.2.4567/build/log.c:3:
/var/lib/dkms/veeamsnap/5.0.2.4567/build/stdafx.h:77:10: fatal error: linux/genhd.h: No such file or directory
   77 | #include <linux/genhd.h> // For basic block driver framework
      |          ^~~~~~~~~~~~~~~
compilation terminated.
In file included from /var/lib/dkms/veeamsnap/5.0.2.4567/build/sparse_bitmap.c:3:
/var/lib/dkms/veeamsnap/5.0.2.4567/build/stdafx.h:77:10: fatal error: linux/genhd.h: No such file or directory
   77 | #include <linux/genhd.h> // For basic block driver framework
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/usr/src/linux-headers-5.18.0-0.bpo.1-common/scripts/Makefile.build:293: /var/lib/dkms/veeamsnap/5.0.2.4567/build/log.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-5.18.0-0.bpo.1-common/scripts/Makefile.build:293: /var/lib/dkms/veeamsnap/5.0.2.4567/build/sparse_bitmap.o] Error 1
In file included from /var/lib/dkms/veeamsnap/5.0.2.4567/build/container.c:3:
/var/lib/dkms/veeamsnap/5.0.2.4567/build/stdafx.h:77:10: fatal error: linux/genhd.h: No such file or directory
   77 | #include <linux/genhd.h> // For basic block driver framework
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/usr/src/linux-headers-5.18.0-0.bpo.1-common/scripts/Makefile.build:293: /var/lib/dkms/veeamsnap/5.0.2.4567/build/container.o] Error 1
In file included from /var/lib/dkms/veeamsnap/5.0.2.4567/build/mem_alloc.c:3:
/var/lib/dkms/veeamsnap/5.0.2.4567/build/stdafx.h:77:10: fatal error: linux/genhd.h: No such file or directory
   77 | #include <linux/genhd.h> // For basic block driver framework
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/usr/src/linux-headers-5.18.0-0.bpo.1-common/scripts/Makefile.build:293: /var/lib/dkms/veeamsnap/5.0.2.4567/build/mem_alloc.o] Error 1
make: *** [/usr/src/linux-headers-5.18.0-0.bpo.1-common/Makefile:1858: /var/lib/dkms/veeamsnap/5.0.2.4567/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.18.0-0.bpo.1-amd64'

**Comment by SergeiShtepa** [comment]
Further support of new kernels for the veeamsnap module is not planned.
Starting from VAL 6.0, work on fresh kernels will be provided by the [blksnap](https://github.com/veeam/blksnap) module.
We are trying to offer the blksnap module in upstream. See [issue#2](https://github.com/veeam/blksnap/issues/2).

**Comment by csandazoltan** [comment]
> Further support of new kernels for the veeamsnap module is not planned. Starting from VAL 6.0, work on fresh kernels will be provided by the [blksnap](https://github.com/veeam/blksnap) module. We are trying to offer the blksnap module in upstream. See [issue#2](https://github.com/veeam/blksnap/issues/2).

Thank you. I understand the words, but i don't understand the meaning. I fairly new to the linux server landscape
What is VAL? What is upstream?

How can I make my Veeam Agent for Linux do snapshot backups while that "VAL 6.0" happens?
Can i switch veeamsnap to blksnap now?

Currently rolling back from last backup before distro upgrade, so i'm going to stay 5.16, but that is not a solution

**Comment by SergeiShtepa** [comment]
VAL - Veeam Agent for Linux.
upstream - Linux [kernel](https://www.kernel.org/).
Veeam users can contact the support service. To begin with, you can write on the [forum](https://forums.veeam.com/veeam-agents-for-linux-mac-aix-solaris-f41/).
[See](https://forums.veeam.com/veeam-agents-for-linux-mac-aix-solaris-f41/fedora-33-kernel-5-8-t70158.html).

**Comment by Fantu** [comment]
useful information: veeam agent for linux 6.0 was released and support kernel from version 2.6.32 to version 6.1 (should use veeamsnap for older kernel and blksnap for newer)
https://www.veeam.com/veeam_agent_linux_6_0_release_notes_rn.pdf

**Comment by veeam** [comment]
AS other participants have pointed out, newer kernels are supported by blksnap.
The issues is closed.
