### ISSUE TITLE
Change block tracking map is always zeroes on newer kernels (>5.11) 

### ISSUE THREAD

**Issue by Dany9966** [veeam/veeamsnap#33]
Every time we create new snapshots on machines that have kernel versions >=5.11, the CBT bitmap is always returned as a bunch of zeros, whereas on older kernels this works as expected (I.E. Ubuntu 20.04 with kernel 5.4).

This was first identified on Ubuntu 22.04 machines, that run kernel 5.15 by default. We tested Ubuntu 20.04 as well, works well by default. Once we upgrade Ubuntu 20.04's kernel from 5.4 to 5.15, the same behavior occurs. Every snapshot returns zeroed CBT map. 

Have you encountered this so far?

`veeamsnap` has been built from master on all machines.

**Comment by Dany9966** [comment]
@SergeiShtepa @CodeImp Can you also please confirm this?

**Comment by CodeImp** [comment]
Hi.

> the CBT bitmap is always returned as a bunch of zeros
This is possible if bio handling does not work.

Try to trace tracking_make_request(). See tracker_disk_ref().
Maybe genconfig.sh  doesn't work properly. There's a real hell with defines.

See IOCTL_SET_KERNEL_ENTRIES and IOCTL_GET_UNRESOLVED_KERNEL_ENTRIES.
Maybe you haven't figured out how this ioctls work.

I can say that there is no such problem on our product.

---
Have a good hacking.

**Comment by Dany9966** [comment]
Yes, I'm still figuring out how to set kernel entries to bypass the ioctl error. So far I only get one unresolved kernel entry everytime I call that. Do you happen to know how exactly are multiple unresolved kernel entries separated? By comma, space, something else? 

As for this particular issue, how can I help BIO not handling properly? Because all the IOCTL calls are successful, so I can't really identify if something is wrong or not.

**Comment by CodeImp** [comment]
> So far I only get one unresolved kernel entry everytime I call that. Do you happen to know how exactly are multiple unresolved kernel entries separated? By comma, space, something else?

I think the answer is in the source code:

```
int ke_get_unresolved(char *buf, size_t max_size)
{
    size_t src_len = 0;
    int buf_ofs = 0;
    int ke_inx;

    for (ke_inx = 0; ke_inx < KE_SIZE; ke_inx++) {
        if (ke_addr_table[ke_inx].addr)
            continue;
        
        src_len = strlen(ke_addr_table[ke_inx].name);
        if ((src_len + 1) > (max_size - buf_ofs))
            return -ENOSPC;

        strcpy(buf + buf_ofs, ke_addr_table[ke_inx].name);
        buf_ofs += (src_len + 1);
    }
    return buf_ofs;
}
```

> Because all the IOCTL calls are successful, so I can't really identify if something is wrong or not.

I think the best solution would be to find code that works reliably and use debugging tools.
And then, if you're going to use this code, you need to understand it well, otherwise you won't be able to maintain it.
I think, you can start by documenting the code in the form of comments, as is customary in the Linux kernel. Maybe it would be a useful job. I may consider your merge requests.

Unlike veeamsnap, the blksnap module was created to offer it to the upstream. Therefore, there are libraries, tests and documentation. Such excesses were not provided for veeamsnap.

**Comment by Dany9966** [comment]
Hey @CodeImp! 
So I've figured out and integrated the whole kernel entry workflow, haven't gotten any not found ioctl calls since then. But this CBT bitmap issue persists. Whenever running kernel versions >= 5.12, the device bitmap is always returned as an array of zeroes, and I haven't noticed any errors in the veeamsnap logs. Not sure yet what causes it, any idea?

**Comment by SergeiShtepa** [comment]
> So I've figured out and integrated the whole kernel entry workflow, haven't gotten any not found ioctl calls since then. 

great.

> But this CBT bitmap issue persists

We need to localize the problem. 
The easiest way to do this is to add debugging logs. You can use KGDB, but I usually have enough logs.
Add trace log to
* cbt_map_set() - for ordinal tracking,
* cbt_map_set_both()  - for track changes in snapshot

You can add call cbt_print_state()  in cbt_map_switch(), log_dump() - uncomment and use it to output arrays of data.

Perhaps the tracker works, but it is the ioctl itself that does not work.
Add logs to ioctl_tracking_read_cbt_map(). Add logs for readbitmap.offset and readbitmap.length.
Maybe you just don't increase the offset parameter.

Read comment for IOCTL_BLK_SNAP_TRACKER_READ_CBT_MAP  in https://github.com/veeam/blksnap/blob/master/module /blksnap.h . It works the same way.

**Comment by Dany9966** [comment]
Hello! 
I've been taking a look and comparing results. Here's our use-case for now:

When reading cbt info, we never iterate it using ioctl, meaning we always read the whole cbt map at once by always passing offset=0 and length=40960 to the `ioctl_tracking_read_cbt_map` call.
I have also added the `cbt_print_state(cbt_map)` call inside `cbt_map_switch()`, and noticed it always logs `changed sectors=0`, while on other working systems there always is a value to it. Therefore, it seems to me that it's not ioctl to blame here.

What do you think I should be checking next?

**Comment by SergeiShtepa** [comment]
Hi.

Of course it would be great to show the log...
It would be interesting to see the value `cbt_map->active`.
> changed sectors=0

This means the cbt_map_set() is not called, never. 
It should be called from tracker_cbt_bitmap_set().  And it, in turn, is called from tracking_make_request().
Add logs and make sure that the bio handling does not work.
And it may not work if the tracker_disk_ref() function has not worked correctly.
Check what logs this function outputs and whether a define VEEAMSNAP_DISK_SUBMIT_BIO is declared.

I think the code is not executed in your case:
```
    {/* change original disks fops */
        unsigned long cr0 = disable_page_protection();
        barrier();

        disk->fops = &tr_disk->fops;
        barrier();

        reenable_page_protection(cr0);
        barrier();
    }
```
This is possible if the KE_BLK_MQ_SUBMIT_BIO function is not set.
But you said:
> So I've figured out and integrated the whole kernel entry workflow, 

In general, the logs of the tracker_disk_ref() function should clarify the situation.

**Comment by SergeiShtepa** [comment]
` receive unsupported command. Device [251:0], command 0x2285` - it`s ok.

It looks like everything is working correctly.
The log shows that the tracker was attached correctly.
Perhaps no disk write transactions were made?
```
[  +0.000064] veeamsnap:defer_io   0 MiB was processed
[  +0.000013] veeamsnap:defer_io   0 MiB was copied
```
These log lines show us that COW was also not executed.

```
[  +0.000003] veeamsnap:tracking   Add to tracking device vda
[  +0.000002] veeamsnap:tracking   fs not found
```
these log lines show that the handling is performed for the vda disk.
virtio paravirtual disk is supported.

If there are partitions on the disk, then you need to attach the tracker to the block devices of these partitions.
When attaching the tracker to the disk and to his partition, a situation of deadlock is possible. Be careful.

Also I see that there is no file system on the disk. 

Therefore, I have doubts that some write transactions were performed to disk.
You may have written to disk, but the data remained in the page cache.

I would suggest repeating the experiment with the partition on the disk and the file system created on it. 
You can use generate_block_MB(). See: https://github.com/veeam/blksnap/blob/master/tests/3000-cbt.sh
Maybe drop_cache() can be useful.

If it seems to you that my thought is nonsense, I still have no others :).

**Comment by Dany9966** [comment]
> The log shows that the tracker was attached correctly.
> Perhaps no disk write transactions were made?
> Also I see that there is no file system on the disk.

There is a filesystem on the disk. Actually, the disk added to tracking contains the actual operating system, so there is no way some kind of disk change to occur, as I've seen on other working systems: every incremental snapshot will always return some change blocks. This system does not. The `fs not found` message I get on every system I have tested on, even though there are filesystems on the tracked disks. 

> You may have written to disk, but the data remained in the page cache.

I could retry with a `sync` before creating another snapshot, but iirc, I have already tried that before.

**Comment by SergeiShtepa** [comment]
> There is a filesystem on the disk. Actually, the disk added to tracking contains the actual operating system, so there is no way some kind of disk change to occur,

It seems to me that it is enough to create several files on this mounted file system with your operating system.
Moreover, you can mount the file system from the snapshot image in RW mode. You can create several files on the snapshot and see that the CBT data has changed.

> The fs not found message I get on every system I have tested on, even though there are filesystems on the tracked disks.

It's very strange.
Here is an example of my logs. 
```
[27.12.2022 19:03:24-134778] <572956> ctrl_fops  | Set address for function blk_mq_submit_bio
[27.12.2022 19:03:24-134797] <572956> ctrl_fops  | Collecting tracking devices:
[27.12.2022 19:03:24-134798] <572956> tracking   | There are no devices under tracking
[27.12.2022 19:03:24-135226] <572956> tracking   | Adding device [8:1] under tracking
[27.12.2022 19:03:24-135233] <572956> tracker    | Create tracker for device [8:1]. Start 0x800 sector, capacity 0x7e17000 sectors
[27.12.2022 19:03:24-135234] <572956> cbt_map    | CBT map create
[27.12.2022 19:03:24-135234] <572956> cbt_map    | Allocate CBT map of 258232
[27.12.2022 19:03:24-135289] <572956> cbt_map    | New CBT generation ID: [288beef7-8d1f-480d-9d54-00f12c1387b3]
[27.12.2022 19:03:24-207788] <572956> tracker    | New tracker disk create
[27.12.2022 19:03:24-207793] <572956> tracker    | The disk's fops is being substituted.
[27.12.2022 19:03:24-207794] <572956> tracker    | New tracker disk was created
[27.12.2022 19:03:24-208018] <572956> tracking   | Add to tracking device sda1
[27.12.2022 19:03:24-208018] <572956> tracking   | fs id: sda1
[27.12.2022 19:03:24-216069] <572956> snapstore  | Create snapstore with id [2443542d-3e98-4f16-8c52-418a0b8b76f1]
```
Debian 11 with kernel v5.16.
```
[    0.000000] Linux version 5.16.0-1-amd64 (debian-kernel@lists.debian.org) (gcc-11 (Debian 11.2.0-16) 11.2.0, GNU ld (GNU Binutils for Debian) 2.37.90.20220130) #1 SMP PREEMPT Debian 5.16.7-2 (2022-02-09)
```

I am sure that if the fs id is not output, then the file system is not detected. The problem may be hiding here.

Probably still something is not in the kernel, but in the features of your infrastructure.  It is possible that not the devices you work with fall under tracking.
Perhaps it makes sense to try on some ordinary system (physical server or full virtualization).
Perhaps I could say something in more detail if I saw the output of the lsblk and mount utilities, full dmesg output and /etc/os-release, but first try the ordinary system.

**Comment by Dany9966** [comment]
Hello @SergeiShtepa! 

So I've been experimenting further, got some results. Can confirm that if you set the actual partition to tracking, CBT works as expected.

I'll give my use-case example below:
Output for lsblk:
```
NAME                      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0                       7:0    0 63.2M  1 loop /snap/core20/1738
loop1                       7:1    0 63.3M  1 loop /snap/core20/1778
loop2                       7:2    0 91.8M  1 loop /snap/lxd/23991
loop3                       7:3    0 49.6M  1 loop /snap/snapd/17883
loop4                       7:4    0 49.8M  1 loop /snap/snapd/17950
loop5                       7:5    0 91.9M  1 loop /snap/lxd/24061
sr0                        11:0    1 1024M  0 rom  
vda                       252:0    0   10G  0 disk 
├─vda1                    252:1    0    1M  0 part 
├─vda2                    252:2    0  907M  0 part /boot
└─vda3                    252:3    0  9.1G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0  9.1G  0 lvm  /
vdb                       252:16   0   10G  0 disk /mnt/snapstores/snapstore_files
```

Now, as you can see, the device we're trying to track is vda (252:0). CBT for this does not work. I tried tracking `253:0` instead, and that works. `vdb` is where I save the snapshot data. 

For our user-case, we set the whole disk device to tracking (just the parent physical disk, not the partitions, so there's no risk of deadlocking), as we do not care what partitions the disk has, we want to snapshot all of its blocks and keep track of raw data changes. This has worked so far, besides the newer kernels mentioned above. Is there no way around this? Why does it matter whether the tracked device has a filesystem or not?

**Comment by SergeiShtepa** [comment]
Very well.
Now I know more about your environment and I have a hypothesis.
Please check it, because I may be wrong.

See: `tracking_make_request()`.
```
        bi_sector = bio_bi_sector( bio );
        bi_size = bio_bi_size(bio);
#ifdef VEEAMSNAP_BDEV_BIO
        if (SUCCESS == tracker_find_by_bdev(bio->bi_bdev, &tracker)){
#else
        if (SUCCESS == tracker_find_by_queue_and_sector( tr_disk, bi_sector, &tracker )){
#endif
```
See: stdafx.h
```
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,12,0)
# ifndef VEEAMSNAP_BDEV_BIO
#  define VEEAMSNAP_BDEV_BIO
# endif
#endif
```
As a result, for the latest versions of the kernel (>=5.12), the tracker is searched by the pointer to the block device.
But pay attention to how the remapping is performed in the [kernel](https://elixir.bootlin.com/linux/v5.12.19/source/block/blk-core.c#L744).
```
/*
 * Remap block n of partition p to block n+start(p) of the disk.
 */
static int blk_partition_remap(struct bio *bio)
{
	struct block_device *p = bio->bi_bdev;

	if (unlikely(should_fail_request(p, bio->bi_iter.bi_size)))
		return -EIO;
	if (bio_sectors(bio)) {
		bio->bi_iter.bi_sector += p->bd_start_sect;
		trace_block_bio_remap(bio, p->bd_dev,
				      bio->bi_iter.bi_sector -
				      p->bd_start_sect);
	}
	bio_set_flag(bio, BIO_REMAPPED);
	return 0;
}
```
That is, when remapping, the pointer to the block device does not change.
Therefore, bios after remapping are not handled.
This is not a problem for VAL, since snapshots are created for partitions.

To solve your problem, you will have to abandon the function tracker_find_by_bdev() . It is enough to search by "queue_request".

It is noteworthy that for blksnap, the filter search is performed the same way.
```
static inline bool bdev_filters_apply(struct bio *bio)
{
	bool completed;
	struct bdev_filter *flt;
	struct bdev_extension *ext;

	spin_lock(&bdev_extension_list_lock);
#if defined(HAVE_BI_BDISK)
	ext = bdev_extension_find_part(bio->bi_disk, bio->bi_partno);
#else
	ext = bdev_extension_find_bdev(bio->bi_bdev);
#endif
	spin_unlock(&bdev_extension_list_lock);
```
and
```
static inline struct bdev_extension *bdev_extension_find_bdev(struct block_device *bdev)
{
	struct bdev_extension *ext;

	if (list_empty(&bdev_extension_list))
		return NULL;

	list_for_each_entry (ext, &bdev_extension_list, link)
		if (bdev == ext->bdev)
			return ext;

	return NULL;
}
```

And version for [upstream](https://lore.kernel.org/linux-block/20221209142331.26395-3-sergei.shtepa@veeam.com/) too.
```
[diff](https://lore.kernel.org/linux-block/20221209142331.26395-3-sergei.shtepa@veeam.com/#iZ31block:blk-core.c) --git a/block/blk-core.c b/block/blk-core.c
index 5487912befe8..284b295a7b23 100644
--- a/block/blk-core.c
+++ b/block/blk-core.c
@@ -678,9 +678,24 @@ void submit_bio_noacct_nocheck(struct bio *bio)
 	 * to collect a list of requests submited by a ->submit_bio method while
 	 * it is active, and then process them after it returned.
 	 */
-	if (current->bio_list)
+	if (current->bio_list) {
 		bio_list_add(&current->bio_list[0], bio);
-	else if (!bio->bi_bdev->bd_disk->fops->submit_bio)
+		return;
+	}
+
+	if (bio->bi_bdev->bd_filter && !bio_flagged(bio, BIO_FILTERED)) {
+		bool pass;
+
+		pass = bio->bi_bdev->bd_filter->fops->submit_bio_cb(bio);
+		bio_set_flag(bio, BIO_FILTERED);
+		if (!pass) {
+			bio->bi_status = BLK_STS_OK;
+			bio_endio(bio);
+			return;
+		}
+	}
+
+	if (!bio->bi_bdev->bd_disk->fops->submit_bio)
 		__submit_bio_noacct_mq(bio);
 	else
 		__submit_bio_noacct(bio);
```
The problem is that the approach that you use does not match the one that is proposed in the upstream.

You can tweak the veeamsnap and blksnap modules to suit your methodology. But it will be more difficult to change a module that has already in upstream. 

Perhaps you need to follow the [work](https://github.com/veeam/blksnap/issues/2) in this direction.  I am sure that your comments may be of interest to the community.
However, you will have to prepare weighty arguments why you need to perform tracking at the disk level.
It's not clear to me yet.

**Comment by veeam** [comment]
veeamsnap project is deprecated and is replaced with blksnap for kernel 5.3.18+.
