### ISSUE TITLE
Support for Linux 6.1

### ISSUE THREAD

**Issue by ddimension** [veeam/veeamsnap#34]
The driver cannot be compiled under Linux 6.1. There are several problems that do not make a solution as simple as expected. 
Are there any plans to support current stable kernels?

**Comment by Fantu** [comment]
hi, see https://github.com/veeam/veeamsnap/issues/31#issuecomment-1162965878

**Comment by Fantu** [comment]
useful information: veeam agent for linux 6.0 was released and support kernel from version 2.6.32 to version 6.1 (should use veeamsnap for older kernel and blksnap for newer)
https://www.veeam.com/veeam_agent_linux_6_0_release_notes_rn.pdf
