### ISSUE TITLE
Linux 5.7.0-3: failed to compile

### ISSUE THREAD

**Issue by terrigan** [veeam/veeamsnap#6]
Same issue as **Linux 5.6: failed to compile** would be my guess

`Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.7.0-3-MANJARO -C /usr/lib/modules/5.7.0-3-MANJARO/build M=/var/lib/dkms/veeamsnap/4.0.0.1961/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.7.0-3-MANJARO (x86_64)
Error while configuring 
Consult /var/lib/dkms/veeamsnap/4.0.0.1961/build/make.log for more information.
.
.
Running post-transaction hooks...
Arming ConditionNeedsUpdate...
Install DKMS modules
==> dkms install veeamsnap/4.0.0.1961 -k 5.6.15-1-MANJARO
==> dkms install veeamsnap/4.0.0.1961 -k 5.7.0-3-MANJARO
Error! Bad return status for module build on kernel: 5.7.0-3-MANJARO (x86_64)
Error while configuring 
Consult /var/lib/dkms/veeamsnap/4.0.0.1961/build/make.log for more information.
==> Warning, `dkms install veeamsnap/4.0.0.1961 -k 5.7.0-3-MANJARO' returned 10
Transaction successfully finished.
[make.log](https://github.com/veeam/veeamsnap/files/4748123/make.log)
`

**Comment by k0ste** [comment]
Please see pinned post at AUR. Use this PKGBUILD and veeamsnap package will be builded flawless.
I think AUR maintainer should update the sources for AUR users, to avoid doubles of issues to this repo.

**Comment by k0ste** [comment]
Fixed in #5

**Comment by terrigan** [comment]
The PKGBUILD in the AUR for 5.7 fixed my issue.

**Comment by CodeImp** [comment]
fixed in 4.0.1.2365
